language: csharp
solution: AlphabetWar.sln

install:
  - nuget restore AlphabetWar.sln
  - nuget install NUnit.ConsoleRunner -Version 3.8.0 -OutputDirectory packages

script:
  - xbuild /p:Configuration=Release AlphabetWar.sln
  - mono ./packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./UnitTests/bin/Release/UnitTests.dll
