language: csharp
solution: AlphabetWar.sln

install:
  - nuget restore AlphabetWar.sln
  - nuget install NUnit.Runners -Version 3.8.0

script:
  - xbuild /p:Configuration=Release AlphabetWar.sln
  - mono ./packages/NUnit.Runners.3.8.0/tools/nunit-console.exe ./UnitTests/bin/Release/UnitTests.dll
